### ISSUE TITLE
/root/.nvm/v0.10.40/bin/forever: No such file or directory

### ISSUE THREAD

**Issue by 24js** [anselal/wekan#1]
I get this error when i try to start service , installed on a clean ubuntu 14.0.4 

```
 /etc/init.d/wekan: line 31: /root/.nvm/v0.10.40/bin/forever: No such file or directory
```

**Comment by anselal** [comment]
Did you run the script using sudo ? You should login as root and then run the script. Did you get any error messages while running the script ?

**Comment by 24js** [comment]
yes i did , i just checked logs ,  it seems https://raw.git..... , urls in shell give port 443: Connection refused , so nvm , nodejs , .. are not installed

**Comment by 24js** [comment]
am i able to run this parts manually 

```
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.28.0/install.sh | bash

source ~/.nvm/nvm.sh
source ~/.profile
source ~/.bashrc

# Make node, npm, available to all users
# n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin; sudo cp -r $n/{bin,lib,share} /usr/local

NODE_VERSION="v0.10.40"

nvm install $NODE_VERSION
nvm use $NODE_VERSION
nvm alias default $NODE_VERSION

npm install forever -g
```

and using http , instead of https

**Comment by anselal** [comment]
The "raw.githubusercontent.com" site redirects you to https. Yes, you can run these lines manually and then try to start the service. If You have problems with wget, you can try with curl like this:

``` sh
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
```

**Comment by 24js** [comment]
curl did the trick , thank you

**Comment by anselal** [comment]
You are welcome. I am glab it worked !!

**Comment by pabloab** [comment]
I've just download `autoinstall_wekan.sh` directly from github, `chmod +x`, run it with `sudo` (with a sudoer) on Ubuntu Server 14.4 LTS. At the end restart and now with `sudo service wekan` start throw me that error.

**Comment by anselal** [comment]
Login as root. Download script. Execute. The script must run as root, not with sudo.

**Comment by whmcsjosh** [comment]
This is still not solved. I just tried to install Wekan and it doesn't work at all. I just get the following error!

```
root@ubuntu-1gb-nyc3:~# /etc/init.d/wekan start
Starting Wekan
root@ubuntu-1gb-nyc3:~# /etc/init.d/wekan: line 32: /root/.nvm/v0.10.40/bin/forever: No such file or directory
```

**Comment by anselal** [comment]
@whmcsjosh Did you get any error messages when you run the script ?

**Comment by lpdrummerboy87** [comment]
Apologies, I was posting from the wrong GitHub account. Yes, I get that error when trying to run wan after running the install script. I attempted a clean install on a fresh Ubuntu 14.04.5 x64 server from DigitalOcean. Please see my attached screenshot as this is the server I selected.

![digital ocean ubuntu droplet](https://cloud.githubusercontent.com/assets/12712673/18129019/6522cdaa-6f4e-11e6-8267-77c4b7f0e9d6.png)

I'm really excited to try out Wekan but I just couldn't seem to get it installed. Can you try on clean Ubuntu 14.04.5 x64 server and see if you get the same error?

**Comment by lpdrummerboy87** [comment]
This was the error:

```
root@ubuntu-1gb-nyc3:~# /etc/init.d/wekan start
Starting Wekan
root@ubuntu-1gb-nyc3:~# /etc/init.d/wekan: line 32: /root/.nvm/v0.10.40/bin/forever: No such file or directory
```

**Comment by anselal** [comment]
@lpdrummerboy87 To be clear. Do you get any errors/warnings when you run the installation script, not when try to start the service ? Can you check if the file /root/.nvm/v0.10.40/bin/forever exist ? Maybe it is not in your PATH. If you red the README, there is a Wekan Virtual Appliance available you can try..

**Comment by lpdrummerboy87** [comment]
I must have done something wrong last time I tried. I just got it to work!

```
Installation completed.

You can run the service manually or you can reboot your system.
Please select one of the following:
1) Start the wekan service
2) Reboot your system
3) Exit
Choice: 1
Starting Wekan
root@wekan:~/wekan-master# info:    Forever processing file: main.js
```

Apologies for reopening this and thanks for the quick response. Everything seems to be working fine now!

**Comment by Gelmes** [comment]
If you are trying to just install I found this link helpful
https://discourse.wekan.io/t/install-within-plesk/572

Install wekan using 'snap' (I didn't now what it was but its a package manager, you might already have it in your linux os)
`sudo snap install wekan`

**Comment by yuppox** [comment]
Ubuntu 16.04.3 LTS
Logged in as root and tried to install.

```You can run the service manually or you can reboot your system.
Please select one of the following:
1) Start the wekan service
2) Reboot your system
3) Exit
Choice: 1
bash: /root/.nvm/v0.10.40/bin/forever: No such file or directory
Starting Wekan
/etc/init.d/wekan: line 37: /root/.nvm/v0.10.40/bin/forever: No such file or directory
```

I guess there were some errors from npm but I'm not sure. I tried again and definitely saw a problem with npm:

`npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js`

I installed with snap instead. It seems like the script needs to check npm and nodejs, if possible.
