### ISSUE TITLE
How to setup MAIL_URL

### ISSUE THREAD

**Issue by hiniesta** [anselal/wekan#14]
I want to config MAIL_URL. Looks like env varaibles are not working. Have try to output other varaibles as PORT an MONGO_URL, but there are all in blank.
Thanks!

**Comment by anselal** [comment]
Sorry for the delayed answer. Can you give me more information ? Are you editing the file and the parameters remain empty ?

**Comment by anselal** [comment]
This issue was moved to wekan/wekan-autoinstall#4
