### ISSUE TITLE
VM user and password

### ISSUE THREAD

**Issue by Erwanaac** [anselal/wekan#16]
Hi
I've installed the last vm, and everything's ok but the user/password  wekan/wekan is refused. 
Could you help me ?
Erwan

**Comment by anselal** [comment]
That is the password for the console log in. To login to the web ui you can create an account through the ui.

**Comment by Erwanaac** [comment]
Thanks
I just discover it 15 mn ago, I don't really know how work wekan , I install it for coworker and thought it was the admin account of the app.
