### ISSUE TITLE
Update manual installation

### ISSUE THREAD

**Issue by Mattes1000** [anselal/wekan#17]
I tried to update an installation made by your autoinstall_wekan.sh script.

I execute the following script as root:

```
/etc/init.d/wekan stop
cd
wget https://github.com/wekan/wekan/releases/download/v0.11.0-rc2/wekan-0.11.0-rc2.tar.gz
rm -rf ~/bundle
tar xzvf wekan-0.11.0-rc2.tar.gz
/etc/init.d/wekan start
```

after that i see in my log file (/run/Wekan.log)
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
```

Did I miss something?

**Comment by anselal** [comment]
@Mattes1000 You are not the first who experienced problems with the fibers module. At the time, I tested my script only with wekan versions 0.9.0 and 0.10.1 so unfortunately I cannot provide any feedback.

**Comment by Mattes1000** [comment]
I could find out that the version v0.11.0-rc2 needs at least node v0.10.41 because meteor need this. 

So I installed this Version via nvm and tweaked your script to this 
[autoinstall_wekan.sh.txt](https://github.com/anselal/wekan/files/657140/autoinstall_wekan.sh.txt)

Now I got it

**Comment by anselal** [comment]
Did this solve your problem with the fibers module ?

**Comment by Mattes1000** [comment]
I could run the script without error. 
But I think I installed the version fibers-1.0.13 manually 
Sorry.. but I tried a lot :)

**Comment by anselal** [comment]
Great job. Thank you for the feedback
