### ISSUE TITLE
Wekan no longer active, your work should be based on wefork

### ISSUE THREAD

**Issue by HLFH** [anselal/wekan#18]
Hi,

@anselal Wekan is no longer active since September or even more, your work should be based on Wefork.

https://github.com/wefork/wekan/

For example, with wefork, you have "[Start- and Duedate for cards](https://github.com/wefork/wekan/pull/26)" feature.

What do you think? :)

I love your Wekan auto-installation script!

**Comment by HLFH** [comment]
FYI @anselal, a Wefork release could come: https://github.com/wefork/wekan/issues/50

**Comment by anselal** [comment]
@HLFH Thank you for your kind words. I can take a look at wefork/wekan probably at 2017 cause now I am on vacation. Although as I see at https://github.com/wefork/wekan/wiki/Install-from-source the instructions are pretty clear, maybe there is no need for my script.

**Comment by HLFH** [comment]
I wish you good vacation.

Ubuntu 14.04 users who don't use systemd in their production server need your great Wekan auto-installation script. Or I will fork your script for Wefork, if you think there is "no need", but I'm sure we need your script with a small update :) What's your choice?

**Comment by anselal** [comment]
I think I could take a look and try to modify my script to suit Wefork/wekan.

**Comment by jLouzado** [comment]
Maybe the main README should be updated to list wefork/wekan as the main repo now?

**Comment by HLFH** [comment]
Now that Wefork and Wekan have merged together, can you @anselal update your script? Thanks. https://github.com/wekan/wekan

**Comment by anselal** [comment]
I will do that as soon a stable release comes out.

**Comment by anselal** [comment]
This issue was moved to wekan/wekan-autoinstall#3
