### ISSUE TITLE
Location of the files

### ISSUE THREAD

**Issue by adamgdynia** [anselal/wekan#19]
Hi! I'm playing with wekan - yesterday I have successfully started a virtual machine on xen with your implementation of wekan - great job! 

I have three questions:
1. In order to change files [(example)](https://github.com/wekan/wekan/pull/593/commits/29e7aeff5db50889b92bf8430246f9e7df4b8534#diff-78c5d7897b99ad0f0a9a3965725ddeae) - I need to locate the client folder. I've been looking everywhere with no success - can you please point me to the right place?
2. How to make a backup?
3. Is there an instruction of how to update the wekan?

Thanks!
Adam

**Comment by anselal** [comment]
Hi!
1. I do not have the slightest idea. Have you checked inside the installation folder ? 
2. Can you check at var/lib/mongodb ?
3. I am not sure about updating wekan, never tried it myself.

**Comment by adamgdynia** [comment]
Thanks @anselal for answers. I have found some of the original files here:

`wekan@wekan:~/bundle/programs/server/app$ pwd
/home/wekan/bundle/programs/server/app
wekan@wekan:~/bundle/programs/server/app$ ls
config  i18n  models  sandstorm.js  sandstorm.js.map  server
wekan@wekan:~/bundle/programs/server/app$ `

but the client folder is missing here...

So what will happen when there will be a new release? New VM and export->import?

**Comment by anselal** [comment]
There should be a VM. You could always try to install the new version on top of the old one, but before that always keep a backup up. I am not sure if there would be a new release of wekan. If you check issue https://github.com/anselal/wekan/issues/18 you will see that there is a new fork of wekan.

**Comment by adamgdynia** [comment]
I see. I didn't realized that there is no plan for another release, since this is a very good tool where any other options are subscription based without an option for local deployment. Anyhow, thank you for your support and I'm getting back to looking for my missing files!

Cheers,
Adam

**Comment by anselal** [comment]
I figured out where the client folder is that your where looking for. The release file my script download contains a compiled version of wekan, so there is no client folder. If you want to edit the app you must download the source and build it using meteor. If you are OK with my answer reply so we can close this issue

**Comment by anselal** [comment]
This issue was moved to wekan/wekan-autoinstall#2
