### ISSUE TITLE
cannot start wekan

### ISSUE THREAD

**Issue by the4ndy** [anselal/wekan#3]
i spun up a fresh ubuntu 14.04 LTS VM, applied updates etc and then ran the auto install script as instructed. At the end i chose to reboot. Now that its back up wekan isnt answering on 8080 or 80 or anyport according to nmap :(  

when i run service wekan status or start i get the following
/etc/init.d/wekan: line 31: /root/.nvm/v0.10.40/bin/forever: No such file or directory

any ideas?

**Comment by anselal** [comment]
Did you get any error messages during the installation ? Please edit the installation script, comment line 5, uncomment line 7 and run the script again. It seems that 'wget' was unable to fetch nvm. If this fixes the error I will update the script.

**Comment by the4ndy** [comment]
that didnt fix the problem, but running that command separately as root (rather than just running the script via sudo) seemed to do the trick. but ultimatley now i can start wekan but get the following error

 info:    Forever processing file: main.js
error:   Cannot start forever
error:   script /root/bundle/main.js does not exist.

I am going to start over with a fresh VM (ill keep this one alive in case its a simple fix) and try from scratch and see what happens

**Comment by the4ndy** [comment]
info:    Forever processing file: main.js
error:   Cannot start forever
error:   script /root/bundle/main.js does not exist.

I am going to start over with a fresh VM (ill keep this one alive in case its a simple fix) and try from scratch and see what happens

**Comment by the4ndy** [comment]
i fixed it, my bad. the problem was that i had downloaded your git repo as a zip and unzipped it, this created a folder with the script in it, i needed to run it at the root of my home directory

**Comment by anselal** [comment]
I am glad it worked for you. I will update the script as soon as I can
