### ISSUE TITLE
can't stop wekan via script

### ISSUE THREAD

**Issue by douyux** [anselal/wekan#5]
/etc/init.d/wekan

stop() {
        if [ -f $PIDFILE ]; then
                echo "Shutting down $NAME"
                rm -f $PIDFILE
                RETVAL=$?
        else
                echo "$NAME is not running."
                RETVAL=0
        fi
}

just delete the pid file, not stop process

**Comment by anselal** [comment]
Run `forever list`, mark the PID and then run `forever stop PID` or just `forever stopall`
I will update the script accordingly

**Comment by anselal** [comment]
`forever stopall` will stop all processes running with forever, so it is not safe. Better run as root `cat /var/run/Wekan.pid | xargs forever stop`. Reply if this worked so we can close this issue and merge the code.

**Comment by douyux** [comment]
thanks, it's works for me
