### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by deanpcmad** [anselal/wekan#8]
Hey, I'm trying to use this script but I'm getting this error while installing:

``` bash
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v3.9.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/bundle/programs/server/npm-debug.log
```

The end of that file is as follows:

```
1706 silly install fibers@1.0.5 /root/bundle/programs/server/node_modules/.staging/fibers-03372e07
1707 info lifecycle fibers@1.0.5~install: fibers@1.0.5
1708 verbose lifecycle fibers@1.0.5~install: unsafe-perm in lifecycle false
1709 verbose lifecycle fibers@1.0.5~install: PATH: /root/.nvm/v0.10.40/lib/node_modules/npm/bin/node-gyp-bin:/root/bundle/programs/server/node_modules/fibers/node_modules/.bin:/root/bundle/programs/server/node_modules/.bin:/root/.nvm/v0.10.40/bin:/root/.nvm/v0.10.40/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
1710 verbose lifecycle fibers@1.0.5~install: CWD: /root/bundle/programs/server/node_modules/fibers
1711 silly lifecycle fibers@1.0.5~install: Args: [ '-c', 'node ./build.js' ]
1712 info lifecycle fibers@1.0.5~install: Failed to exec install script
1713 verbose unlock done using /root/.npm/_locks/staging-820139a9dfb8dad0.lock for /root/bundle/programs/server/node_modules/.staging
1714 silly rollbackFailedOptional Starting
1715 silly rollbackFailedOptional Finishing
1716 silly runTopLevelLifecycles Starting
1717 silly runTopLevelLifecycles Finishing
1718 silly install printInstalled
1719 warn meteor-dev-bundle@0.0.0 No description
1720 warn meteor-dev-bundle@0.0.0 No repository field.
1721 warn meteor-dev-bundle@0.0.0 No license field.
1722 verbose stack Error: fibers@1.0.5 install: `node ./build.js`
1722 verbose stack spawn ENOENT
1722 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/v0.10.40/lib/node_modules/npm/lib/utils/spawn.js:17:16)
1722 verbose stack     at ChildProcess.emit (events.js:98:17)
1722 verbose stack     at maybeClose (child_process.js:766:16)
1722 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1723 verbose pkgid fibers@1.0.5
1724 verbose cwd /root/bundle/programs/server
1725 error Linux 3.19.0-25-generic
1726 error argv "node" "/root/.nvm/v0.10.40/bin/npm" "install"
1727 error node v0.10.40
1728 error npm  v3.9.2
1729 error file sh
1730 error code ELIFECYCLE
1731 error errno ENOENT
1732 error syscall spawn
1733 error fibers@1.0.5 install: `node ./build.js`
1733 error spawn ENOENT
1734 error Failed at the fibers@1.0.5 install script 'node ./build.js'.
1734 error Make sure you have the latest version of node.js and npm installed.
1734 error If you do, this is most likely a problem with the fibers package,
1734 error not with npm itself.
1734 error Tell the author that this fails on your system:
1734 error     node ./build.js
1734 error You can get information on how to open an issue for this project with:
1734 error     npm bugs fibers
1734 error Or if that isn't available, you can get their info via:
1734 error     npm owner ls fibers
1734 error There is likely additional logging output above.
1735 verbose exit [ 1, true ]
```

Any ideas? I'm running this on a clean Ubuntu 14.04 server machine but I had the same issue on Ubuntu 16.04 server too

**Comment by anselal** [comment]
I googled for issues regarding fibers@1.0.5. It seems there is some problem with Ubuntu 14. Can you try to install fibers manually using `npm install fibers@1.0.5 -g`. This will install it globally. After that rerun the script to see what happens.

**Comment by deanpcmad** [comment]
Just tried that and I get the same error:

``` bash
root@server:~# source ~/.nvm/nvm.sh
root@server:~# source ~/.profile
root@server:~# source ~/.bashrc
root@server:~# npm install fibers@1.0.5 -g

> fibers@1.0.5 install /root/.nvm/v0.10.40/lib/node_modules/fibers
> node ./build.js

sh: 1: node: Permission denied
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install" "fibers@1.0.5" "-g"
npm ERR! node v0.10.40
npm ERR! npm  v3.9.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by deanpcmad** [comment]
Actually not to worry, I'm using the Docker image now and that works a treat :smile:

**Comment by SS-TN** [comment]
Hi guys, 
i'm facing the same error, and tried npm install fibers@1.0.5 -g , didn't work. 
Trying to install Wekan on Debian GNU/Linux 8 (jessie) amd64 built on 2016-06-06 , i'm using GCP .. 

> npm WARN meteor-dev-bundle@0.0.0 No description
> npm WARN meteor-dev-bundle@0.0.0 No repository field.
> npm WARN meteor-dev-bundle@0.0.0 No license field.
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install"
> npm ERR! node v0.10.40
> npm ERR! npm  v3.9.6
> npm ERR! code ELIFECYCLE
> npm ERR! fibers@1.0.5 install: `node ./build.js`
> npm ERR! Exit status 8
> npm ERR! 
> npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the fibers package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./build.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs fibers
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls fibers
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     
> 
> /root/bundle/programs/server/npm-debug.log 

and here's the log 

> ```
> 1707 warn meteor-dev-bundle@0.0.0 No description
> 1708 warn meteor-dev-bundle@0.0.0 No repository field.
> 1709 warn meteor-dev-bundle@0.0.0 No license field.
> 1710 verbose stack Error: fibers@1.0.5 install: `node ./build.js`
> 1710 verbose stack Exit status 8
> 1710 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/v0.10.40/lib/node_modules/npm/lib/utils/lifecycl$
> 1710 verbose stack     at EventEmitter.emit (events.js:98:17)
> 1710 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/v0.10.40/lib/node_modules/npm/lib/utils/spawn.js$
> 1710 verbose stack     at ChildProcess.emit (events.js:98:17)
> 1710 verbose stack     at maybeClose (child_process.js:766:16)
> 1710 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
> 1711 verbose pkgid fibers@1.0.5
> 1712 verbose cwd /root/bundle/programs/server
> 1713 error Linux 3.16.0-4-amd64
> 1714 error argv "node" "/root/.nvm/v0.10.40/bin/npm" "install"
> 1715 error node v0.10.40
> 1716 error npm  v3.9.6
> 1717 error code ELIFECYCLE
> 1718 error fibers@1.0.5 install: `node ./build.js`
> 1718 error Exit status 8
> 1719 error Failed at the fibers@1.0.5 install script 'node ./build.js'.
> 1719 error Make sure you have the latest version of node.js and npm installed.
> 1719 error If you do, this is most likely a problem with the fibers package,
> 1719 error not with npm itself.
> 1719 error Tell the author that this fails on your system:
> 1719 error     node ./build.js
> 1719 error You can get information on how to open an issue for this project with:
> 1719 error     npm bugs fibers
> 1719 error Or if that isn't available, you can get their info via:
> 1719 error     npm owner ls fibers
> 1719 error There is likely additional logging output above.
> 1720 verbose exit [ 1, true ]
> ```

Help please :/

**Comment by anselal** [comment]
Obviously this is a fiber error.
