### ISSUE TITLE
Wekan - Started but can't Connect

### ISSUE THREAD

**Issue by darkziah** [anselal/wekan#9]
Sir can you help me regarding with this problem. i all ready run the auto script and successfully Started Wekan Service but can't access it.

![wekan](https://cloud.githubusercontent.com/assets/19814619/15886389/cf05ef8e-2d97-11e6-9cb1-0e83934f768a.PNG)

**Comment by anselal** [comment]
@darkziah You can access your installation at http://your-ip:8080 as mentioned in the README file. You can get your ip by running `ifconfig` or `ip addr show` as root

**Comment by cknoll** [comment]
I have the same problem (after running the install script).
Neither http://192.168.178.41:8080 nor http://127.0.0.1:8080 nor localhost:8080 works.

**Comment by TheFonix** [comment]
Yep i have this problem too!

**Comment by anselal** [comment]
Can you ping your virtual machine from your host ?

**Comment by TheFonix** [comment]
Hi anselal, I managed to get it to work work by doing it all manually instead of with the auto make script, but after I installed it I found out that that's it's not a global board, you have per user boards which wasn't what I wanted, but thank you for the support ;)

**Comment by anselal** [comment]
This issue was moved to wekan/wekan-autoinstall#5
